image: conoria/alpine-pandoc

pages:
  script:
  - apk update
  # - apk add curl alpine-sdk autoconf automake bash build-base git graphicsmagick lcms2-dev libjpeg-turbo libjpeg-turbo-dev libpng libpng-dev libtool libwebp libwebp-dev nasm zlib zlib-dev nodejs nodejs-npm
  # - npm install -g gulp
  # - npm i
  - apk add curl alpine-sdk autoconf automake bash build-base
  - mkdir public
  - make html
  artifacts:
    paths:
    - public
  only:
  - master

